name: CI pipeline

on:
  push:
  pull_request:

jobs:
  warcrime-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for warcrimes
        run: |
          if grep -qwi "i love javascript" "README.md"; then
            exit 1
          fi
